# Test file demonstrating basic provider mocking

mock_provider "aws" {}

run "test_bucket_creation" {
  # Test that the bucket is created with the correct name
  variables {
    bucket_name = "test-bucket-name"
    tags = {
      Environment = "test"
      Project     = "mock-testing"
    }
  }

  assert {
    condition     = aws_s3_bucket.my_bucket.bucket == "test-bucket-name"
    error_message = "Bucket name was not set correctly"
  }

  assert {
    condition     = aws_s3_bucket.my_bucket.tags.Environment == "test"
    error_message = "Environment tag was not set correctly"
  }

  assert {
    condition     = aws_s3_bucket.my_bucket.tags.Project == "mock-testing"
    error_message = "Project tag was not set correctly"
  }
}

run "test_versioning_configuration" {
  variables {
    bucket_name = "versioned-bucket"
  }

  assert {
    condition     = aws_s3_bucket_versioning.versioning.versioning_configuration[0].status == "Enabled"
    error_message = "Versioning was not enabled"
  }
}

run "test_generated_attributes" {
  variables {
    bucket_name = "generated-data-test"
  }

  # These attributes are generated by the mock provider
  assert {
    condition     = aws_s3_bucket.my_bucket.arn != ""
    error_message = "Bucket ARN was not generated"
  }

  assert {
    condition     = aws_s3_bucket.my_bucket.bucket_domain_name != ""
    error_message = "Bucket domain name was not generated"
  }

  # Note: Generated data follows specific patterns:
  # - Strings: 8 character random alphanumeric
  # - Numbers: 0
  # - Booleans: false
  # - Collections: empty
}