apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webserver.fullname" . }}-secret
  labels:
    {{- include "webserver.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.dbPasswordBase64 }}
  API_KEY: {{ .Values.secret.apiKeyBase64 }}
