apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver-deployment
  labels:
    app: webserver
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: nginx
        image: nginx
        command: ["sh", "-c", "envsubst '$APP_ENV $MAX_CONNECTIONS' < /tmp/template/index.html > /usr/share/nginx/html/index.html && envsubst '$APP_ENV $MAX_CONNECTIONS' < /tmp/template/docs.html > /usr/share/nginx/html/docs.html && nginx -g 'daemon off;'"]
        ports:
        - containerPort: 80
        # Inject Key/Value ConfigMap data as Environment Variables (Bulk)
        # envFrom:
        # - configMapRef:
        #     name: webserver-configmap
        # Selective Key/Value Environment Variables Injection
        env:
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: webserver-configmap
              key: APP_ENV
        - name: MAX_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: webserver-configmap
              key: MAX_CONNECTIONS
        # Secret Injection (Decoded from Base64)
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: webserver-secret
              key: DB_PASSWORD
        resources:
          requests:
            memory: "150Mi"
          limits:
            memory: "300Mi"
        # Startup Probe (Protects slow-booting applications)
        startupProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        # Mount File ConfigMap template as Volume Mount
        volumeMounts:
        - name: nginx-index-file
          mountPath: "/tmp/template/"
      volumes:
      - name: nginx-index-file
        configMap:
          name: webserver-configmap
          # Selective Projection: Only mount index.html as a file
          items:
          - key: index.html
            path: index.html
          - key: docs.html
            path: docs.html

