apiVersion: v1
kind: Secret
metadata:
  name: webserver-secret
  labels:
    app: webserver
type: Opaque
data:
  # Base64 encoded strings:
  # 'supersecret' -> c3VwZXJzZWNyZXQ=
  # '12345-abcde' -> MTIzNDUtYWJjZGU=
  DB_PASSWORD: "c3VwZXJzZWNyZXQ="
  API_KEY: "MTIzNDUtYWJjZGU="
