# Test file demonstrating Coder provider mocking
#
# coder/coder v2 schema:
#   DATA SOURCES: coder_workspace, coder_workspace_owner, coder_parameter
#   RESOURCES:    coder_agent, coder_app
#
# mock_provider "coder" {} generates fake computed values for all of these.

mock_provider "coder" {}

run "test_workspace_data_source" {
  # data.coder_workspace.me is auto-populated by the mock.
  # Verify the workspace name and owner outputs are present (non-null).
  assert {
    condition     = output.workspace_name != null
    error_message = "Workspace name output should be present"
  }

  assert {
    condition     = output.workspace_owner != null
    error_message = "Workspace owner output should be present"
  }
}

run "test_agent_created" {
  # coder_agent is a real resource; the mock provider generates an ID for it.
  assert {
    condition     = output.agent_id != ""
    error_message = "Agent ID should be generated by the mock provider"
  }
}

run "test_parameter_defaults" {
  # Verify parameter data sources expose the correct static metadata.
  assert {
    condition     = data.coder_parameter.cpu.name == "CPU"
    error_message = "CPU parameter name should be 'CPU'"
  }

  assert {
    condition     = data.coder_parameter.cpu.default == "2"
    error_message = "CPU default should be '2'"
  }

  assert {
    condition     = data.coder_parameter.cpu.mutable == true
    error_message = "CPU parameter should be mutable"
  }

  assert {
    condition     = data.coder_parameter.memory.name == "Memory (GB)"
    error_message = "Memory parameter name should be 'Memory (GB)'"
  }

  assert {
    condition     = data.coder_parameter.memory.default == "4"
    error_message = "Memory default should be '4'"
  }

  assert {
    condition     = length(data.coder_parameter.cpu.option) == 3
    error_message = "CPU parameter should have 3 options"
  }

  assert {
    condition     = length(data.coder_parameter.memory.option) == 3
    error_message = "Memory parameter should have 3 options"
  }
}

run "test_apps_created" {
  # coder_app resources should be (mock) created with the correct static values.
  assert {
    condition     = coder_app.code_server.url == "http://localhost:8080"
    error_message = "code-server URL should be http://localhost:8080"
  }

  assert {
    condition     = coder_app.code_server.display_name == "VS Code"
    error_message = "code-server display name should be 'VS Code'"
  }

  assert {
    condition     = coder_app.terminal.slug == "terminal"
    error_message = "Terminal app slug should be 'terminal'"
  }

  assert {
    condition     = output.code_server_url == "http://localhost:8080"
    error_message = "code_server_url output should match"
  }
}